import React from 'react';

const SCALE = 0.8; // 전체 UI를 100% 크기로 유지

// 모든 숫자 값을 스케일에 맞게 조정하는 헬퍼 함수
const scaleValue = (value: string | number): string => {
  if (typeof value === 'number') return `${value * SCALE}px`;
  if (typeof value === 'string') {
    const match = value.match(/^(\d+(?:\.\d+)?)(px|rem|em)$/);
    if (match) {
      const [, num, unit] = match;
      return `${parseFloat(num) * SCALE}${unit}`;
    }
  }
  return value;
};

// 스타일 객체의 모든 크기 관련 속성을 스케일링
const scaleStyles = (styles: React.CSSProperties): React.CSSProperties => {
  const scaled: any = {};
  const sizeProps = ['fontSize', 'padding', 'margin', 'marginTop', 'marginBottom', 'marginLeft', 'marginRight', 
                     'paddingTop', 'paddingBottom', 'paddingLeft', 'paddingRight', 'gap', 'borderRadius',
                     'width', 'height', 'maxWidth', 'maxHeight', 'minWidth', 'minHeight', 'top', 'right', 'bottom', 'left'];
  
  for (const [key, value] of Object.entries(styles)) {
    if (sizeProps.includes(key) && (typeof value === 'string' || typeof value === 'number')) {
      scaled[key] = scaleValue(value);
    } else {
      scaled[key] = value;
    }
  }
  return scaled;
};

const rawStyles: { [key: string]: React.CSSProperties } = {
  pageContainer: {
    display: 'flex',
    flexDirection: 'row',
    height: '100vh',
    fontFamily: "'Pretendard', sans-serif",
    backgroundColor: '#f8f9fa',
    overflow: 'hidden',
  },
  chatColumn: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    borderRight: '1px solid #e9ecef',
    padding: '24px',
    height: '100vh',
    boxSizing: 'border-box',
    color: '#000000',
    width: '450px',
    minWidth: '350px',
    flexShrink: 0,
    zIndex: 10,
    boxShadow: '2px 0 12px rgba(0,0,0,0.03)',
  },
  chatHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  chatTitle: {
    margin: 0,
    fontSize: '26px',
    fontWeight: 800,
    color: '#1b1f24',
    letterSpacing: '-0.5px',
  },
  authContainer: {},
  authButton: {
    padding: '8px 16px',
    background: '#3b82f6',
    color: 'white',
    border: 'none',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 4px rgba(59, 130, 246, 0.2)',
  },
  chatMessagesContainer: {
    flex: 1,
    overflowY: 'auto',
    padding: '10px 4px',
    marginBottom: '16px',
    scrollBehavior: 'smooth',
  },
  messageBubble: {
    maxWidth: '88%',
    padding: '16px 20px',
    borderTopLeftRadius: '20px',
    borderTopRightRadius: '20px',
    borderBottomRightRadius: '20px',
    borderBottomLeftRadius: '20px',
    lineHeight: 1.65,
    marginBottom: '16px',
    wordBreak: 'break-word',
    fontSize: '15px',
    letterSpacing: '-0.3px',
    whiteSpace: 'pre-line',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
  },
  userBubble: {
    backgroundColor: '#2563eb',
    color: '#ffffff',
    marginLeft: 'auto',
    borderBottomRightRadius: '4px',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.15)',
  },
  assistantBubble: {
    background: '#f1f5f9',
    color: '#1e293b',
    marginRight: 'auto',
    borderBottomLeftRadius: '4px',
    border: '1px solid #e2e8f0',
  },
  savedTripsContainer: {
    borderTop: '1px solid #f1f5f9',
    paddingTop: '16px',
    marginTop: '8px',
  },
  savedTripsSummary: {
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '13px',
    color: '#64748b',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    transition: 'color 0.2s',
  },
  savedTripsList: {
    maxHeight: '150px',
    overflowY: 'auto',
    marginTop: '12px',
    paddingRight: '4px',
  },
  savedTripItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 12px',
    borderBottom: '1px solid #f1f5f9',
    fontSize: '14px',
    borderRadius: '8px',
    transition: 'background 0.2s',
    cursor: 'pointer',
  },
  loadButton: {
    padding: '4px 10px',
    fontSize: '11px',
    background: '#0ea5e9',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  deleteTripButton: {
    padding: '4px 8px',
    fontSize: '11px',
    background: 'transparent',
    color: '#ef4444',
    border: '1px solid #fecaca',
    borderRadius: '12px',
    cursor: 'pointer',
    marginLeft: '6px',
    fontWeight: 600,
  },
  chatInputForm: {
    display: 'flex',
    gap: '12px',
    marginTop: '10px',
    position: 'relative',
  },
  chatInput: {
    flex: 1,
    padding: '14px 16px',
    border: '1px solid #e2e8f0',
    borderRadius: '24px',
    fontSize: '15px',
    color: '#1e293b',
    backgroundColor: '#f8fafc',
    transition: 'all 0.2s',
    outline: 'none',
    boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.02)',
  },
  sendButton: {
    padding: '0 20px',
    background: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '24px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 700,
    boxShadow: '0 4px 6px rgba(37, 99, 235, 0.2)',
    transition: 'transform 0.1s, box-shadow 0.1s',
  },
  tripColumn: {
    flex: 1,
    height: '100vh',
    overflowY: 'auto',
    padding: '32px',
    boxSizing: 'border-box',
    color: '#000000',
    backgroundColor: '#f8f9fa',
    position: 'relative',
  },
  tripLoading: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: '#64748b',
  },
  travelAnimation: {
    position: 'relative',
    width: '200px',
    height: '200px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  globe: {
    width: '120px',
    height: '120px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 20px 50px rgba(59, 130, 246, 0.3)',
    animation: 'rotateGlobe 8s linear infinite',
  },
  globeInner: {
    fontSize: '64px',
    animation: 'rotateGlobe 8s linear infinite',
  },
  airplane: {
    position: 'absolute',
    fontSize: '42px',
    animation: 'floatPlane 3s ease-in-out infinite',
    filter: 'drop-shadow(0 8px 16px rgba(0,0,0,0.15))',
    zIndex: 10,
  },
  tripError: {
    padding: '24px',
    margin: 'auto',
    maxWidth: '400px',
    textAlign: 'center',
    backgroundColor: '#fef2f2',
    borderRadius: '16px',
    border: '1px solid #fee2e2',
    color: '#991b1b',
    boxShadow: '0 4px 12px rgba(239, 68, 68, 0.1)',
  },
  tripWelcome: {
    textAlign: 'center',
    margin: 'auto',
    color: '#64748b',
    maxWidth: '500px',
  },
  welcomeTitle: {
    fontSize: '28px',
    fontWeight: 800,
    color: '#1e293b',
    marginBottom: '16px',
    letterSpacing: '-0.5px',
  },
  welcomeText: {
    fontSize: '16px',
    lineHeight: 1.6,
    marginBottom: '32px',
  },
  quickPromptContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    justifyContent: 'center',
    marginTop: '24px',
  },
  quickPromptChip: {
    padding: '10px 16px',
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '20px',
    fontSize: '14px',
    color: '#475569',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 4px rgba(0,0,0,0.03)',
  },
  tripResultContainer: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100%',
    maxWidth: '1400px',
    margin: '0 auto',
    width: '100%',
  },
  tripHeader: {
    marginBottom: '24px',
    paddingBottom: '24px',
    borderBottom: '1px solid #e2e8f0',
  },
  tripMeta: {
    display: 'flex',
    gap: '20px',
    color: '#64748b',
    marginTop: '12px',
    fontSize: '15px',
    fontWeight: 500,
  },
  tripActions: {
    display: 'flex',
    gap: '12px',
    marginTop: '20px',
  },
  primaryBtn: {
    padding: '10px 18px',
    background: '#2563eb',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    boxShadow: '0 4px 6px rgba(37, 99, 235, 0.2)',
    transition: 'transform 0.1s, box-shadow 0.1s',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  outlineBtn: {
    padding: '10px 18px',
    background: '#ffffff',
    color: '#475569',
    border: '1px solid #cbd5e1',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  totalBudgetText: {
    fontSize: '20px',
    fontWeight: '800',
    color: '#059669',
    marginTop: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  tripBody: {
    display: 'flex',
    flexDirection: 'row',
    minHeight: 0,
  },
  itineraryPane: {
    flex: '1 1 0',
    minWidth: 0,
    overflowY: 'auto',
    paddingRight: '12px',
    minHeight: 0,
  },
  mapPane: {
    position: 'sticky',
    top: '0',
    height: 'calc(100vh - 250px)',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 10px 30px rgba(0,0,0,0.08)',
    border: '1px solid #e2e8f0',
    display: 'flex',
    flexDirection: 'column',
  },
  mapDayFilter: {
    display: 'flex',
    gap: '8px',
    padding: '12px',
    background: 'rgba(255,255,255,0.9)',
    backdropFilter: 'blur(8px)',
    borderBottom: '1px solid rgba(0,0,0,0.05)',
    overflowX: 'auto',
    flexShrink: 0,
  },
  dayContainer: {
    background: '#ffffff',
    borderRadius: '12px',
    padding: '16px',
    boxShadow: '0 2px 6px rgba(15, 23, 42, 0.08)',
    border: '1px solid #edf2f7',
    marginBottom: '30px',
  },
  dayHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: '8px',
  },
  dayTitleGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  dayTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 700,
    color: '#1b1f24',
  },
  dayBudget: {
    fontSize: '13px',
    color: '#495057',
  },
  dayActions: {
    display: 'flex',
    gap: '8px',
    marginBottom: '12px',
  },
  itineraryList: {
    listStyle: 'none',
    padding: 0,
  },
  itineraryItem: {
    position: 'relative',
    marginBottom: '15px',
    background: 'white',
    padding: '15px',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
    border: '1px solid #e9ecef',
  },
  itemHeader: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '10px',
  },
  itemTime: {
    background: '#eef6ff',
    color: '#005fcc',
    padding: '5px 10px',
    borderRadius: '15px',
    marginRight: '10px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  placeName: {
    fontWeight: 'bold',
    fontSize: '16px',
    flex: 1,
  },
  dragHandle: {
    cursor: 'grab',
    padding: '5px',
    color: '#6c757d',
  },
  itemDescription: {
    margin: '8px 0',
    color: '#495057',
    fontSize: '14px',
    cursor: 'pointer',
    whiteSpace: 'pre-wrap',
  },
  inlineInput: {
    border: '1px solid #007bff',
    outline: 'none',
    background: '#eef6ff',
    width: '80px',
    textAlign: 'center',
  },
  inlineTextarea: {
    width: '100%',
    border: '1px solid #007bff',
    borderRadius: '4px',
    padding: '8px',
    fontSize: '14px',
    minHeight: '60px',
    resize: 'vertical',
  },
  itemReason: {
    margin: '8px 0',
    background: '#f1f3f5',
    padding: '8px',
    borderRadius: '4px',
    fontSize: '13px',
  },
  detailsContainer: {
    marginTop: '10px',
    fontSize: '13px',
    color: '#343a40',
  },
  detailItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '5px',
  },
  detailIcon: {
    fontSize: '16px',
  },
  expenseInput: {
    width: '100px',
    padding: '4px',
    border: '1px solid #007bff',
    borderRadius: '4px',
  },
  expenseText: {
    cursor: 'pointer',
    color: '#007bff',
    fontWeight: 'bold',
  },
  itemActions: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    display: 'flex',
    gap: '5px',
  },
  actionButton: {
    background: 'transparent',
    border: '1px solid #adb5bd',
    color: '#495057',
    fontSize: '12px',
    cursor: 'pointer',
    padding: '4px 6px',
    borderRadius: '6px',
  },
  deleteButton: {
    background: 'transparent',
    border: 'none',
    color: '#dc3545',
    fontSize: '20px',
    cursor: 'pointer',
  },

  addPlaceButton: {
    width: '100%',
    padding: '10px',
    marginTop: '10px',
    border: '2px dashed #007bff',
    borderRadius: '8px',
    background: 'rgba(0, 123, 255, 0.05)',
    color: '#007bff',
    fontSize: '14px',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
};

// 모든 스타일을 80% 스케일로 적용
export const styles = Object.fromEntries(
  Object.entries(rawStyles).map(([key, value]) => [key, scaleStyles(value)])
);
