import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { TripData, ItineraryItem } from '../types/trip';
import { sanitizeText } from './text';

// Helper to load Korean font
export const loadKoreanPdfFont = async (pdf: jsPDF): Promise<string | null> => {
  const fontName = 'NotoSansKR';
  // Use CDN URL for static font instead of variable font
  const fontUrl = 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2107@1.1/Pretendard-Regular.woff';
  
  // Alternative: Use a simpler approach with a reliable static font
  const staticFontUrl = 'https://fonts.gstatic.com/ea/notosanskr/v2/NotoSansKR-Regular.woff2';

  try {
    // Try to load from local first
    let res = await fetch('/fonts/NotoSansKR-Regular.ttf');
    if (!res.ok) {
      console.log('Local font not found, trying CDN...');
      // Fallback to CDN
      res = await fetch('https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-kr@5.0.0/files/noto-sans-kr-korean-400-normal.woff');
    }
    
    if (!res.ok) {
      console.error('Font fetch failed:', res.status);
      return null;
    }
    
    const blob = await res.blob();
    const reader = new FileReader();
    
    return new Promise((resolve) => {
      reader.onloadend = () => {
        try {
          const b64 = (reader.result as string).split(',')[1];
          pdf.addFileToVFS('NotoSansKR.ttf', b64);
          pdf.addFont('NotoSansKR.ttf', fontName, 'normal');
          pdf.setFont(fontName);
          console.log('Korean font loaded successfully');
          resolve(fontName);
        } catch (err) {
          console.error('Font processing error:', err);
          resolve(null);
        }
      };
      reader.onerror = (err) => {
        console.error('FileReader error:', err);
        resolve(null);
      };
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    console.error('Failed to load Korean font:', e);
    return null;
  }
};

export const generatePremiumPDF = async (trip: TripData): Promise<boolean> => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const fontName = await loadKoreanPdfFont(doc);
  
  if (!fontName) {
    return false;
  }
  
  const baseFont = fontName;
  doc.setFont(baseFont);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // --- 1. COVER PAGE ---
  // Background accent
  doc.setFillColor(240, 248, 255); // AliceBlue
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Title
  doc.setFontSize(32);
  doc.setTextColor(34, 62, 120); // Dark Blue
  doc.setFont(baseFont, 'bold');
  const titleLines = doc.splitTextToSize(sanitizeText(trip.tripTitle), pageWidth - (margin * 2));
  doc.text(titleLines, pageWidth / 2, 80, { align: 'center' });

  // Subtitle (Destination & Period)
  doc.setFontSize(16);
  doc.setTextColor(100, 100, 100);
  doc.setFont(baseFont, 'normal');
  doc.text(`${sanitizeText(trip.destination)} | ${sanitizeText(trip.period)}`, pageWidth / 2, 100, { align: 'center' });

  // Keywords
  if (trip.keywords) {
    doc.setFontSize(12);
    doc.setTextColor(120, 120, 120);
    doc.text(`#${sanitizeText(trip.keywords).replace(/, /g, ' #')}`, pageWidth / 2, 110, { align: 'center' });
  }

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Trip Planner AI', pageWidth / 2, pageHeight - 20, { align: 'center' });

  // --- 2. OVERVIEW PAGE ---
  doc.addPage();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, 'F'); // White bg

  doc.setFontSize(22);
  doc.setTextColor(34, 62, 120);
  doc.setFont(baseFont, 'bold');
  doc.text('Trip Overview', margin, 30);

  // Budget Summary
  const totalBudget = trip.days.reduce((sum, day) => 
    sum + day.itinerary.reduce((dSum, item) => dSum + (item.expense || 0), 0), 0
  );

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('💰 예상 총 경비', margin, 50);
  
  doc.setFontSize(24);
  doc.setTextColor(31, 122, 46); // Green
  doc.setFont(baseFont, 'bold');
  doc.text(`${totalBudget.toLocaleString()}원`, margin, 62);

  // Travel Tips Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(250, 250, 250);
  doc.roundedRect(margin, 80, pageWidth - (margin * 2), 60, 3, 3, 'FD');

  doc.setFontSize(14);
  doc.setTextColor(34, 62, 120);
  doc.text('✈️ Travel Tips', margin + 5, 90);

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.setFont(baseFont, 'normal');
  const tips = [
    '• 여권 유효기간이 6개월 이상 남았는지 확인하세요.',
    '• 현지 전압과 플러그 모양을 미리 확인하고 어댑터를 챙기세요.',
    '• 비상시를 대비해 대사관 연락처를 저장해두세요.',
    '• 여행자 보험 가입을 권장합니다.'
  ];
  let tipY = 100;
  tips.forEach(tip => {
    doc.text(tip, margin + 5, tipY);
    tipY += 7;
  });

  // --- 3. DAILY ITINERARY ---
  trip.days.forEach((day, index) => {
    doc.addPage();
    
    // Day Header
    doc.setFontSize(18);
    doc.setTextColor(34, 62, 120);
    doc.setFont(baseFont, 'bold');
    doc.text(`Day ${day.day} - Itinerary`, margin, 20);

    // Daily Budget
    const dailyBudget = day.itinerary.reduce((sum, item) => sum + (item.expense || 0), 0);
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(`Daily Budget: ${dailyBudget.toLocaleString()}원`, pageWidth - margin, 20, { align: 'right' });

    // Table
    const tableBody = day.itinerary.map(item => [
      item.time,
      sanitizeText(item.place),
      sanitizeText(item.description),
      item.expense ? `${item.expense.toLocaleString()}원` : '-'
    ]);

    autoTable(doc, {
      startY: 30,
      head: [['Time', 'Place', 'Description', 'Expense']],
      body: tableBody,
      styles: {
        font: fontName || 'helvetica',
        fontStyle: 'normal',
        fontSize: 10,
        cellPadding: 4,
      },
      headStyles: {
        fillColor: [34, 62, 120],
        textColor: 255,
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { cellWidth: 20 }, // Time
        1: { cellWidth: 40, fontStyle: 'bold' }, // Place
        2: { cellWidth: 'auto' }, // Description
        3: { cellWidth: 30, halign: 'right' }, // Expense
      },
      alternateRowStyles: {
        fillColor: [245, 247, 250],
      },
      margin: { left: margin, right: margin },
    });
  });

  doc.save(`${trip.tripTitle || 'trip'}_premium.pdf`);
  return true;
};

export const generateImagePDF = (imgData: string, width: number, height: number, title: string) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  const imgWidth = pageWidth;
  const imgHeight = height * imgWidth / width;
  
  let heightLeft = imgHeight;
  let position = 0;

  doc.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
  heightLeft -= pageHeight;

  while (heightLeft > 0) {
    position = heightLeft - imgHeight;
    doc.addPage();
    doc.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }
  
  doc.save(`${title}.pdf`);
};
